version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DB_CONNECTION=null
      - DB_HOST=127.0.0.1
      - DB_PORT=3306
      - DB_DATABASE=
      - DB_USERNAME=
      - DB_PASSWORD=
    volumes:
      - .:/var/www/html
    command: ["php", "artisan", "serve", "--host=0.0.0.0", "--port=8000"]
