version: '3.8'

services:
  laravel-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app-container
    volumes:
      - .:/var/www
    ports:
      - "9000:9000"

  webserver:
    image: nginx:latest
    container_name: laravel-nginx
    volumes:
      - .:/var/www
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    depends_on:
      - laravel-app
