version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
    - DB_CONNECTION=pgsql
    - DB_HOST=dpg-cqp8t4aj1k6c73dfa0ng-a
    - DB_PORT=5432
    - DB_DATABASE=prune
    - DB_USERNAME=prune_user
    - DB_PASSWORD=pX62h2kSeoiWlNmfB6DcHi3q0pmK8AJr

    volumes:
      - .:/var/www/html
    command: ["php", "artisan", "serve", "--host=0.0.0.0", "--port=8000"]
