version: '3.8'

services:
  web:
    image: nginx:latest
    container_name: my-nginx
    volumes:
      - .:/var/www/html
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    depends_on:
      - php

  php:
    build:
      context: .
    container_name: my-php
    volumes:
      - .:/var/www/html
    expose:
      - "9000"




